email:
  - email_1: teste_autimacaaooo@gmail.com
    email_existente: teste_qa@gmail.com
    login: user_qa@teste.com
    vazio:

password:
  - pass1: user123
    vazio:

gerar_token:
  - email: user_qa@teste.com
    senha: user123